-- Territorios: tablas Supabase para la página Netlify y sincronización con Access
-- Ejecutar en: Supabase Dashboard → SQL Editor → New query → Run

-- ---------------------------------------------------------------------------
-- Tablas
-- ---------------------------------------------------------------------------

create table if not exists public.datos_semana (
  id bigint generated by default as identity primary key,
  canal text not null default 'publica',
  exportado timestamptz not null default now(),
  datos jsonb not null,
  constraint datos_semana_canal_key unique (canal)
);

comment on table public.datos_semana is 'Paquete semanal (salidas, responsables, territorios, exportado) publicado desde Access o mapa.html hacia Supabase.';
comment on column public.datos_semana.canal is 'Clave estable para UPSERT; la fila publica (Netlify) usa canal=publica.';
comment on column public.datos_semana.datos is 'Objeto JSON: exportado, version, salidas[], responsables[], territorios[].';

create table if not exists public.acciones_colaboradores (
  id bigint generated by default as identity primary key,
  tipo text not null,
  payload jsonb not null,
  origen text not null default 'predicacion-netlify',
  procesado boolean not null default false,
  creado_en timestamptz not null default now(),
  procesado_en timestamptz
);

comment on table public.acciones_colaboradores is 'Cola de cierres/ajustes hechos en la web; Sync-SupabaseToAccess.ps1 las importa a Access.';

create index if not exists idx_acciones_colaboradores_pendientes
  on public.acciones_colaboradores (procesado, creado_en)
  where procesado = false;

-- ---------------------------------------------------------------------------
-- Row Level Security (clave anon en el navegador)
-- ---------------------------------------------------------------------------

alter table public.datos_semana enable row level security;
alter table public.acciones_colaboradores enable row level security;

drop policy if exists datos_semana_select_anon on public.datos_semana;
create policy datos_semana_select_anon
  on public.datos_semana
  for select
  to anon
  using (true);

drop policy if exists datos_semana_insert_anon on public.datos_semana;
create policy datos_semana_insert_anon
  on public.datos_semana
  for insert
  to anon
  with check (true);

drop policy if exists datos_semana_update_anon on public.datos_semana;
create policy datos_semana_update_anon
  on public.datos_semana
  for update
  to anon
  using (true)
  with check (true);

drop policy if exists acciones_insert_anon on public.acciones_colaboradores;
create policy acciones_insert_anon
  on public.acciones_colaboradores
  for insert
  to anon
  with check (true);

drop policy if exists acciones_select_anon on public.acciones_colaboradores;
create policy acciones_select_anon
  on public.acciones_colaboradores
  for select
  to anon
  using (true);

drop policy if exists acciones_update_anon on public.acciones_colaboradores;
create policy acciones_update_anon
  on public.acciones_colaboradores
  for update
  to anon
  using (true)
  with check (true);

drop policy if exists acciones_delete_anon on public.acciones_colaboradores;
create policy acciones_delete_anon
  on public.acciones_colaboradores
  for delete
  to anon
  using (procesado = false);

-- Publicación Netlify: UPSERT desde mapa.html (servidor local) con canal=publica.
-- Véase SUPABASE.md y sql/alter_datos_semana_canal_upsert.sql si la tabla ya existía sin columna canal.
